List query
activeviam/par-student-spark-atoti pull request #5
Opened 2021-12-01 15:28 UTC by sehyod

2021-12-01 17:19 UTC, OPeyrusse requested changes
Good job overall. I made some suggestions.

2021-12-01 17:19 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/condition/AndCondition.java
> +				.reduce(true, (a, b) -> a && b);
Nice but there is a small performance flaw here. `#reduce` does not have any knowledge of what you are trying to do. As a consequence, it will test every condition, even when one of them is true.
To short-circuit the execution, like standard AND operators do, you should use `Stream#allMatch` as follow:
```suggestion
				.allMatch((filterFunction) -> {
					try {
						return filterFunction.call(row);
					} catch (Exception e) {
						e.printStackTrace();
						return false;
					}
				});
```

2021-12-01 17:19 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/CsvReader.java
> +    public static Dataset<Row> read(String path, SparkSession session) throws URISyntaxException {
Not to be worried anymore by this exception that you will not handled, you can re-throw it as an `IllegalArgumentException` for example.
In java, there is a distinction between checked and unchecked exceptions. Checked exceptions force you to write a `try-catch` to handle them, while unchecked don't.
The new trend of the Java community is to almost never use checked exceptions, as they are setting constraints the signature of the method, preventing its evolution (practice followed by AWS, Google and recommended in Effective Java, a book considered as one of the pilars in Java).

Unless this is something that the user should really be concerned, don't use check exceptions.
Unfortunately, old APIs, likely like Spark, do not always apply this strategy, often for backward compatibility reasons.
At least for this prototype, or in general, it is ok to "hide" these exceptions, particularly as you will not deal with them.

2021-12-01 17:19 UTC, OPeyrusse commented on src/test/java/io/atoti/spark/TestListQuery.java
> +    assertThat(valuesById).containsExactlyEntriesOf(Map.of(3L, -420d));
Oops :disappointed: Good catch

2021-12-01 17:19 UTC, OPeyrusse commented on src/test/java/io/atoti/spark/TestListQuery.java
> +    assertThat(rows).hasSize(1).extracting(rowReader("id")).first().isEqualTo(2);
Why do you need the call to `#first`?

2021-12-02 08:37 UTC, sehyod commented on src/test/java/io/atoti/spark/TestListQuery.java
> +    assertThat(rows).hasSize(1).extracting(rowReader("id")).first().isEqualTo(2);
`#extracting` returns an iterable of the extracted values, so the instance under test becomes an iterable containing `2` but it is not equal to `2`, we need to extract the first (and only) element of the iterable to be able to check its value.

2021-12-02 17:27 UTC, OPeyrusse approved these changes
No objection to the code but suggestions. Feel free to merge if you want.

2021-12-02 17:27 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/ListQuery.java
> +			return Arrays.asList((Row[]) dataframe.select(columns).limit(limit + offset).tail(
You can also use `List#copyOf`, that would create an immutable list (but it does not accept null, which should not happen)

2021-12-02 17:27 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/ListQuery.java
> +			return Arrays.asList((Row[]) dataframe.select(columns).tail(Math.max(dfSize - offset, 0)));
Instead of the max, you could even return an empty list if `offset > dfSize`.

2021-12-08 09:29 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/ListQuery.java
> +		dataframe = dataframe.withColumn("_id", monotonically_increasing_id());
Looks good to me.
Now, try to combine the two APIs: query with limit + offset and conditions.

2021-12-08 10:44 UTC, arnaudframmery commented on src/main/java/io/atoti/spark/ListQuery.java
> +		dataframe = dataframe.withColumn("_id", monotonically_increasing_id());
do you mean in a new method (so a new API) ?

2021-12-08 17:14 UTC, OPeyrusse commented on src/main/java/io/atoti/spark/ListQuery.java
> +		dataframe = dataframe.withColumn("_id", monotonically_increasing_id());
Yes, that's what I had in mind.

2021-12-09 09:09 UTC, merged